### ISSUE TITLE
Profile card desktop

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/your-tribe-for-life-squad-page#11]
Profile cards voor op desktop formaat

Met profile cards worden de kaartjes bedoelt van alle leerlingen

Hieronder is het eerste design geschets:

**Comment by KaanKalmi** [comment]
<img src="https://github.com/user-attachments/assets/94d8d891-656b-4b65-9f11-b806b9e944e3" width=650 height=650>
<img src="https://github.com/user-attachments/assets/71c799aa-6a8f-41fd-880c-cebdbd370a2f" width=650 height=650>

**Comment by KaanKalmi** [comment]
De profile cards voor desktop zijn gefinished vandaag (Check de live link)
