### ISSUE TITLE
Letter form component

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/your-tribe-for-life-squad-page#17]
Maak een component aan in Svelte voor een formulier in brief form. Daarin komt het formulier brief in te staan. Zodat we deze vaker kunnen hergebruiken als component. Handig als het werkt met dynamische data, zodat we het goed kunnen hergebruiken.

**Comment by Lmikkers** [comment]
Het formulier gemaakt in de letterform branche, werkt alleen nog niet het formulier, maar wel een component aangemaakt.
https://github.com/KaanKalmi/your-tribe-for-life-squad-page/tree/letterForm-component-larissa

component naam: `<Brief />` zo kun je hem gebruiken op de pagina.

<img width="802" alt="Scherm­afbeelding 2024-09-13 om 15 20 13" src="https://github.com/user-attachments/assets/fd54f78b-7d63-4f32-ba2f-47b90ddf0e69">

**Comment by KaanKalmi** [comment]
Dit staat ook inmiddels in de main branch en kan je [hier](https://effortless-choux-a35df0.netlify.app/) zien als je klikt op een squad en vervolgens op de knop 'bericht'
