### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/your-tribe-for-life-squad-page#19]

**Comment by yujing-student** [comment]
<h1>component is gemaakt</h1>

![image](https://github.com/user-attachments/assets/d7db6c1d-6f5e-4412-914a-c49c9dffb954)

<h2>link naar files waar ik het nu gebruik</h2>

zie hier de link naar de button.svelte: https://github.com/KaanKalmi/your-tribe-for-life-squad-page/blob/button-component-yujing/src/routes/button.svelte

de link naar de code voor het importeren van de button:
https://github.com/KaanKalmi/your-tribe-for-life-squad-page/blob/ee3c9794804449d01e985cf914d9dff57f22c6d2/src/routes/%2Bpage.svelte#L3-L10

**Comment by yujing-student** [comment]
Dit is gemaakt en gemergd zie de pull request:https://github.com/KaanKalmi/your-tribe-for-life-squad-page/pull/26
