### ISSUE TITLE
Person page layout

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/your-tribe-for-life-squad-page#20]
Maak een pagina voor de detail personen, zodat dit dynamisch werkt met id's. [id] mapje in svelte

**Comment by Lmikkers** [comment]
### Schets gemaakt hoe ik de animatie wil gaan maken:
<img width="396" alt="image" src="https://github.com/user-attachments/assets/2b854e1e-9363-4b71-b6c5-168b7706f41f">

### Schets persoon [id] pagina
<img width="379" alt="image" src="https://github.com/user-attachments/assets/04a5a99a-90a5-4b6b-bcf9-8aafbfbc41cb">

**Comment by Lmikkers** [comment]
Tot nu toe dit gemaakt: En wanneer je op de knop drukt zie je het brief component. En ben bezig met de animatie voor de brief openen.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/4c155d39-46e4-45e4-9d99-173a010d5f7a">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8a10f2f8-cf6d-40ec-a778-44d4aa9b3b8f">

**Comment by Lmikkers** [comment]
Na feedback gekregen te hebben op het design, dat het niet super toegankelijk is , omdat je eerst een knop moet drukken voordat je een bericht kunt sturen. Heb ik ze allebei zichtbaar gemaakt op de pagina. 

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/8422e83d-9ff2-4eff-b2e3-0e582d7d6d20">
