### ISSUE TITLE
Header component (logo & back button)

### ISSUE THREAD

**Issue by Robin1224** [KaanKalmi/your-tribe-for-life-squad-page#22]
We moeten een header aanmaken waarbij we een evt. logo inzetten en/of een titel. Ook moet het een back button bevatten voor als je op de squad pagina zit en terug wilt naar je squad keuze pagina.

**Comment by KaanKalmi** [comment]
Dit is ook gefinished en staat vanaf vandaag in de main branch (Check de live link)
