### ISSUE TITLE
Button component semantischer maken en correct linken

### ISSUE THREAD

**Issue by KaanKalmi** [KaanKalmi/your-tribe-for-life-squad-page#40]
Hey Yu Jing, tijdens het maken van de desktopCards kwam ik erachter dat jouw button component niet semantisch was en ook dus niet ging linken naar waar het moest linken je had namelijk dit als code:

![image](https://github.com/user-attachments/assets/80958996-e77e-4ad4-9aa3-5e5c6466bb70)

Had je niet liever een `<a href="/{person.id}">` kunnen gebruiken en dit vervolgens gestyled naar wat het button zou moeten zijn?

Hierdoor had je het namelijk semantisch gemaakt (aangezien de button moet verwijzen naar een ander pagina) en ook nog is goed gelinkt naar het volgende pagina ipv dat we de `<h1>` een `<a href="/{person.id}">` attribuut meegeven.

Kijk naar deze bronnen voor meer informatie:
- [FreeCodeCamp - Button Link Code Examples](https://www.freecodecamp.org/news/html-button-link-code-examples-how-to-make-html-hyperlinks-using-the-href-attribute-on-tags/)
- [W3C - HTML Hyperlink constraints and admonitions](https://w3c.github.io/html-reference/a.html#a-constraints)

**Comment by yujing-student** [comment]
@KaanKalmi bedankt voor de feedback ik heb er naar gekeken dit is nu de code kan ik een pull request indienen?

```
<a class="buttoncomponent" href="person.id">person.id</a>

<style>
    .buttoncomponent {
        border: none;
        font-size: 1rem;
        padding: .75rem 2rem;
        background-color: rgb(239, 38, 38);
        border-radius: 4px;
        color: white;
        width: max-content;
        cursor: pointer;
        transition: .5s ease-out;
        text-decoration: none;
    }
    .buttoncomponent:hover {
        background-color: rgb(220, 35, 35);
    }
</style>
```

**Comment by KaanKalmi** [comment]
Dit ziet er idd een stuk beter uit, je kan een pull request indienen ja (let op: Je moet wel de juiste repository kiezen en niet FDND-Task)

**Comment by KaanKalmi** [comment]
Ik  merge je pull request niet, ik ga WEL je codde copy/pasten naar mijn branch
